# Generated by Django 6.0.4 on 2026-05-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behaviormonitoring',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='queuereport',
            name='created_at',
        ),
    ]
