# Generated by Django 6.0.4 on 2026-05-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_panel', '0002_remove_behaviormonitoring_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationCenter',
        ),
        migrations.DeleteModel(
            name='OrganizationNotification',
        ),
    ]
