# Generated by Django 6.0.4 on 2026-05-19 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AlterField(
            model_name='queuebooking',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_system.organization'),
        ),
        migrations.AlterField(
            model_name='queuebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queue_system.queuebooking'),
        ),
        migrations.AlterField(
            model_name='token',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_system.organization'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
